# Generated by Django 4.2.2 on 2023-07-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0003_rename_staff_user_is_staff_remove_user_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
